### ISSUE TITLE
Automate Build and Deployment Process

### ISSUE THREAD

**Issue by andrewbates09** [refined-bits/refinedbitspodcast.com#5]
Current Process:
$> export PATH=$PATH:/home/anon/.gem/ruby/2.1.0/bin
1. jekyll build --destination refinedbitspodcast
2. tar -czvf refinedbitspodcast.tar.gz refinedbitspodcast
3. scp refinedbitspodcast.tar.gz user@refinedbitspodcast.com:~/workingsites/
4. tar -xzf refinedbitspodcast.tar.gz
5. cp -r refinedbitspodcast/* /home/refinedbitspodcast/public_html/

One click/command process to come?

**Comment by doingweb** [comment]
Got us [set up on Codeship](https://codeship.com/projects/63379). Builds are green and deployment from master is working as of #40.
